== Breve nota introduttiva

Dopo 30 anni di lavoro sono giunto alla conclusione che sebbene ogni organizzazione abbia i propri difetti e ogni paese e cultura i propri vizi peculiari, sono le persone che creano il clima del luogo di lavoro.
Più contano le persone, più sono in grado di influenzare la qualità del lavoro e il benessere delle persone intorno a loro.

Negli anni ho compilato un catalogo mentale di comportamenti o atteggiamenti ricorrenti -- _red flags_ -- nei quali ravviso segnali forti che c'è qualcosa che non va; non si tratta necessariamente di indicatori di un ambiente tossico ma spesso ne sono precursori.

Per aiutare la memoria e liberarmene ho deciso di raccoglierli man mano che mi capitano sotto il naso.

== La cordata

A costo di risultare scontato, il primo _red flag_ è la cordata. 

La cordata si stabilisce quando un capo sceglie i propri collaboratori applicando, ancor prima dei criteri meritocratici (competenze, esperienza, meriti pregressi, dedizione, creatività, generosità), il criterio della fedeltà personale. 

In cambio della fedeltà a sé, il capo garantisce opportunità che altrimenti sarebbero distribuite anche ad altre persone. 
La logica della cordata è predatoria: si intercettano opportunità e si distribuiscono in maniera non omogenea tra il personale, privilegiando chi più si approssima al capo. In cambio di ciò, si manovra una piccola falange armata personale.

La cordata non è legata alla fiducia nella competenza di persone che si è imparato a conoscere e apprezzare nel tempo; può esistere anche tra persone che non si stimano in termini di qualità professionali ma convengono che meglio insieme che da soli.

La cordata è riconoscibile sia nei periodi di crescita, quando si assiste a carriere folgoranti, sia nei periodi di crisi allorquando, in occasione di transizioni drammatiche e ristrutturazioni aziendali, alcuni cadono sistematicamente in piedi.

Le cordate esistono nel settore pubblico e nel settore privato. Le cordate sono connaturate allo uno stile di _leadership_ individualistico basato sulla esomotivazione; prosperano nelle organizzazioni poco attente alla responsabilità dei _manager_ nella crescita delle risorse e nel mantenimento di un buon clima. 

== L'uso sistematico dell'autorità

L'uso sistematico dell'autorità da parte del capo è un _red flag_.

Il capo costretto a ricorrere sistematicamente alla propria posizione organizzativa per esercitare il controllo e la disciplina è un segnale forte di una organizzazione che ha scelto la persona sbagliata per il ruolo, o di una persona che non è in grado di operare attraverso la sua autorevolezza.

La posizione organizzativa sovraordinata implica, di per sé, autorevolezza. 
Il collega che non sia ancora completamente disilluso assume che il capo scelto dalla organizzazione abbia delle doti che ne supportano il ruolo.
Il lavoratore dipendente medio crede nell'ordinamento gerarchico; il capo che non sia in grado di crearsene una deve quantomeno evitare di distruggere l'aura dell'_endorsement_.

L'autorità è un'arma valida solo perché non viene usata; come la bomba atomica, è un deterrente che non viene mai usato perché magari è efficace ma ha un _blast radius_ difficilmente controllabile, non sempre proporzionale all'effetto desiderato e tale da lasciare un ambiente tossico.

== Tirare la giacchetta

Tirare la giacchetta del capo è un _red flag_.

Ci sono collaboratori -- capetti intermedi o aspiranti tali -- che si fanno spazio evocando il nome del capo. 
Se possibile cercano un contatto diretto, a costo di essere molesti, per avere l'"orecchio del re".
Una volta ottenuto il canale di comunicazione previlegiato (che il superiore concede per cortesia, perché non ne percepisce l'uso futuro, perché non comprende la natura del collaboratore), lo usano come megafono per amplificare le proprie posizioni e la propria capacità d'azione.
Talvolta ciò può comportare lo scavalcamento del capo diretto, la cui autorità viene annullata al ricorso alla _escalation_.

"Mi serve che tu faccia questa cosa subito. Non puoi? Non mi mettere nelle condizioni di dire a X che il [mio, NDR] progetto a cui tiene tanto è andato in ritardo perché tu non mi hai dato la collaborazione richiesta."

== Confondere designazione e conquista

Nelle organizzazioni può capitare che a una posizione di capo concorrano più persone, una sola delle quali sarà designata.

Allorquando il vincitore, anziché sentirsi designato ad aiutare i collaboratori da una posizione di maggiore responsabilità e influenza, si sente conquistatore e abusa della posizione ottenuta per vendicarsi azzerando le _chance_ dei collaboratori sconfitti, si è di fronte a un _red flag_.

Il capo confidente nelle proprie capacità (e nella equità della organizzazione a cui appartiene) ha il compito di promuovere i propri collaboratori. 
Se tra i collaboratori ci sono degli avversari, il capo ha il compito di aiutarli a colmare le lacune che hanno fatto sì che non vincessero la selezione: l'organizzazione avrà a disposizione un bacino di talenti più ampio e saprà riconoscere al capo, oltre alle capacità già dimostrate nel corso della selezione, la generosità nei confronti della organizzazione.

## L'organizzazione disattenta alla generosità

Può anche essere che sia l'organizzazione a non saper riconoscere il valore della generosità; il capo che non aiuta i collaboratori a crescere per paura di essere oscurato può manifestare un elemento di debolezza personale (scarsa confidenza nelle proprie capacità) ma anche una scarsa confidenza nella capacità dell'organizzazione di riconoscere che la crescita dei collaboratori è un elemento di crescita per l'organizzazione ed è ascrivibile anche all'azione del capo, al quale va attribuita parte del merito.

## Cercare il genio o l'eroe

Alcune organizzazioni sono alla costante ricerca del genio individuale o dell'eroe che da solo, offrendo il petto al nemico, sbaraglia le avversità e fa la differenza. A tali individui vengono attribuiti la maggior parte dei meriti, come se non fossero parte di una organizzazione o un gruppo.

Questa caratteristica è un _red flag_; essa evidenzia la scarsa attenzione al fatto che maggiore è la complessità o il volume delle attività condotte, minore la possibilità dell'individuo di fare la differenza se non attraverso la collaborazione. 
Premiare uno per i meriti degli altri ha un profondo effetto demotivante per chi si trova a lavorare suo malgrado per il successo altrui.

Un gruppo sano usa tutte le risorse, prendendo da ciascuno secondo le proprie capacità e le proprie competenze, per raggiungere un obiettivo comune.
Nel lavorare in gruppo non ci si deve preoccupare del fatto che non si riceverà in proporzione al proprio contributo perché l'organizzazione ne sceglierà uno che raccoglierà per tutti.

## Il feudo

Alcune persone tendono a non condividere le proprie conoscenze su ambiti specifici per rendersi insostituibili. 
Si costruisce qualcosa, magari lavorando in segreto a un'idea e tenendo nascosto il prodotto finché non è più o meno completo; poi si costituisce sulla conoscenza esclusiva una posizione di vantaggiofootnote:[Magari facendo leva sul canale di comunicazione previlegiato con il capo superiore (**tirare la giacchetta**), oppure facendo leva sulla propensione della organizzazione a **cercare l'eroe**.].

Questo atteggiamento può nascere dall'insicurezza individuale o dalla erronea concezione che la carriera si costruisca su ciò che si è fatto in passato anziché su ciò che si è capaci di fare nel futuro; gli effetti sono importanti per gli individui e per l'intera organizzazione.
 

Questo atteggiamento è un _red flag_ perché ha diversi effetti collaterali. 

Innanzitutto il risultato ottenuto è quanto può realizzare un singolo: un prodotto amatoriale frutto di uno studio parziale che non considera tutti gli _stakeholder_. 

In secondo luogo, la persona che acquista il proprio feudo perde la possibilità di fare altro. Investe tutto su ciò che ha fatto e rinuncia a sapere fare altro.

Infine, l'organizzazione ostaggio di queste logiche diviene rigida, come lo era il feudalesimo.

La contromisura sta nello spostare l'accento dal merito passato (che tuttavia va apertamente e pubblicamente riconosciuto) al potenziale futuro: si favorisce l'attitudine di chi si mette nelle condizioni di contribuire al futuro dell'organizzazione.
Nel caso in esame, ciò comporta che il "feudatario" condivida ciò che ha fatto con i colleghi affinché essi possano subentrare e/o affiancare, liberando le proprie risorse per nuove attività e sfide.


// == Abusare della posizione

// L'abuso della posizione di capo è un _red flag_.

// La posizione di capo è data perché si possa servire più persone  

== La esomotivazione

I capi (e le organizzazioni) che sanno raccontare il percorso di crescita solo in termini di carriera sono un _red flag_.

Nella visione di queste organizzazioni si cresce perché si guadagnano più soldi, si è riconosciuti influenti dalla organizzazione e dai collaboratori, indipendentemente dall'ambito e dal merito. 
La motivazione è esterna a sé.

I capi endomotivanti 